services:
  victim1:
    image: webdevops/vsftp:latest
    environment:
      - FTP_USER=ftpuser
      - FTP_PASSWORD=pass
    networks:
      myarpnetwork:
        ipv4_address: 192.168.1.2
    container_name: victim1

  victim2:
    build:
      context: ../
      dockerfile: network/client.Dockerfile
    networks:
      myarpnetwork:
        ipv4_address: 192.168.1.3
    container_name: victim2

  attacker:
    build:
      context: ../
      dockerfile: network/attacker.Dockerfile
    privileged: true
    networks:
      myarpnetwork:
        ipv4_address: 192.168.1.4
    container_name: attacker

networks:
  myarpnetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.1.0/24
